### ISSUE TITLE
Losing mouseleave when mouse leaves viewport

### ISSUE THREAD

**Issue by staltz** [cyclejs-community/cyclejs-sortable#12]
I tested in Firefox desktop and if I drag and the mouse goes out of the viewport (e.g. if it goes near the address bar) then my mouseleave isn't computed anymore and it's stuck with dragging.

**Comment by jvanbruegge** [comment]
I did it now with `mouseleave`, but the window selection might be useful too

**Comment by staltz** [comment]
Awesome
