### ISSUE TITLE
Bug when moving an item too quickly

### ISSUE THREAD

**Issue by staltz** [cyclejs-community/cyclejs-sortable#2]
This works because I did it slowly:

![slow](https://cloud.githubusercontent.com/assets/90512/18312145/e412c49a-7510-11e6-914c-754132328d1c.gif)

This doesn't because I moved it quickly:

![fast](https://cloud.githubusercontent.com/assets/90512/18312148/eb5372f4-7510-11e6-931d-b713c918812a.gif)

PS: overall I'm _loving_ the idea of this library and the prospect of making any UI easily sortable with one line of code. I just think it needs some polishing first.

**Comment by jvanbruegge** [comment]
I guess I know the issue, currently it's only possible to swap with the item below or above, this has to be replaced with something that pushes as many items as needed out of the way. I will do this when I get home.

Yeah, some polishing is horribly unterstated :)
