### ISSUE TITLE
Allow for multiple stream libraries

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs-community/cyclejs-sortable#9]
I have to use adapt, but I'm not completely sure if `xs.fromObservable` _just works_ with all stream libs or if I have to do something else for the incoming stream

Maybe @staltz can help here?

**Comment by staltz** [comment]
> xs.fromObservable just works with all stream libs

xs.fromObservable *just works* with all stream libs. Basically RxJS v5, most.js. But recently, also Kefir and Bacon.

**Comment by jvanbruegge** [comment]
That is cool
